version: '3.8'

services:
  web:
    build: .
    command: ["gunicorn", "heatstroke.asgi:application", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb  # Add the environment variable for DB connection

  mqtt:
    build: .
    command: python manage.py mqtt
    volumes:
      - .:/app
    depends_on:
      - db
      

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose port for external connections (optional)

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
volumes:
  pg_data:
  static_volume:
  redis_data:

